import { type NextPage } from "next";
import { useRouter } from "next/router";
import { useUser } from "@clerk/nextjs";
import LoadingSpinner from "~/components/ui/LoadingSpinner";
import { api } from "~/utils/api";
// Alert
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Send } from "lucide-react";

import { SupportForm } from "~/components/dashboard/SupportForm";

const Dashboard: NextPage = () => {
  const { isLoaded, isSignedIn, user } = useUser();
  const subscriptions = api.subscriptions.getMySubscriptions.useQuery(
    {},
    {
      enabled: isLoaded,
    }
  );

  return (
    <>
      {/* <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className="py-16">
        <div className="container space-y-8" style={{ minHeight: "50vh" }}>
          {/* Alert */}
          {!isLoaded && <LoadingSpinner />}

          {isLoaded && (
            <div className="">
              <Alert className="space-y-3 sm:flex">
                <div className="mr-5 hidden sm:block">
                  <Send className="h-full" />
                </div>
                <div className="space-y-2">
                  <AlertTitle className="">Hola {user?.firstName} </AlertTitle>
                  <AlertDescription>
                    Aquí puedes ver y descargar todas tus facturas. Recuerda que
                    si necesitas algo siempre puedes ponerte en contacto con
                    nosotros!
                  </AlertDescription>
                </div>
              </Alert>
            </div>
          )}

          {subscriptions.isLoading && <LoadingSpinner />}
          {!subscriptions.isLoading && (
            <SupportForm
              name={user?.firstName as string}
              //@ts-ignore
              email={user?.primaryEmailAddress?.toString()}
              products={subscriptions.data?.map((s) => s.name) || []}
              support_id={user?.id as string}
            />
          )}
        </div>
      </main>
    </>
  );
};

export default Dashboard;
