import { type NextPage } from "next";
import { useRouter } from "next/router";
import { useUser } from "@clerk/nextjs";
import { Invoice, columns } from "~/components/dashboard/InvoicesTable";
import { DataTable } from "~/components/ui/DataTable/";
import LoadingSpinner from "~/components/ui/LoadingSpinner";
import { api } from "~/utils/api";
// Alert
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Send } from "lucide-react";

const Dashboard: NextPage = () => {
  const router = useRouter();
  const invoiceFilterObj = router.query.subscriptionId
    ? { filter: { subscriptionId: router.query.subscriptionId as string } }
    : {};
  console.log(router.query);
  const { isLoaded, isSignedIn, user } = useUser();
  const invoices = api.invoices.getMyInvoices.useQuery(invoiceFilterObj, {
    enabled: isLoaded,
  });

  return (
    <>
      {/* <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className="py-16">
        <div className="container space-y-8" style={{ minHeight: "50vh" }}>
          {/* Alert */}
          {!isLoaded && <LoadingSpinner />}

          {isLoaded && (
            <Alert className="space-y-3 sm:flex">
              <div className="mr-5 hidden sm:block">
                <Send className="h-full" />
              </div>
              <div className="space-y-2">
                <AlertTitle className="">Hola {user?.firstName} </AlertTitle>
                <AlertDescription>
                  Aquí puedes ver y descargar todas tus facturas. Recuerda que
                  si necesitas algo siempre puedes ponerte en contacto con
                  nosotros!
                </AlertDescription>
              </div>
            </Alert>
          )}

          {/* TABLE */}
          <div>
            {/* LOADING SPINNER */}
            {invoices.isLoading && <LoadingSpinner />}
            {invoices.data && (
              <DataTable columns={columns} data={invoices.data} />
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Dashboard;
