import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { UserButton } from "@clerk/nextjs";
import Inner404 from "~/components/ui/inner404";

const Home: NextPage = () => {
  //const hello = api.example.hello.useQuery({ text: "from tRPC" });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        {/* <UserButton afterSignOutUrl="/" /> */}
        <Inner404></Inner404>
        {/* {hello.data ? hello.data.greeting : "Loading tRPC query..."} */}
      </main>
    </>
  );
};

export default Home;
